version: "3"
services:
  gluetun:
    image: qmcgaw/gluetun
    # line above must be uncommented to allow external containers to connect. See https://github.com/qdm12/gluetun/wiki/Connect-a-container-to-gluetun#external-container-to-gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    volumes:
      - /configs/gluetun:/gluetun
    restart: unless-stopped
    environment:
      # See https://github.com/qdm12/gluetun/wiki
      - VPN_SERVICE_PROVIDER=mullvad
      - VPN_TYPE=openvpn
      # OpenVPN:
      - OPENVPN_USER="USER_id"
      - restart:always
      # Timezone for accurate log times
      # Server list updater. See https://github.com/qdm12/gluetun/wiki/Updating-Servers#periodic-update
      - UPDATER_PERIOD=24h
      - SERVER_CITIES=Dallas TX,Los Angeles CA,New York NY
    ports:
      - 8888:8888/tcp 
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
      - 5678:5678
      - 8989:8989
      - 7878:7878
      - 9117:9117
      - 7575:7575 
  transmission:
    image: lscr.io/linuxserver/transmission:latest
    container_name: transmission
    environment:
      - PUID=1000
      - PGID=1000
    network_mode: "service:gluetun"
    volumes:
      - /config/transmission:/config
      - /data/torrents:/downloads 

    restart: unless-stopped
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - /config/sonarr:/config 
      - /data/media/tv:/data/tv
      - /data/torrents:/downloads
    network_mode: "service:gluetun"
    restart: unless-stopped
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    network_mode: "service:gluetun"
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - /config/radarr:/config
      - /data/media/movies:/data/movies #optional
      - /data/torrents:/data/torrents
    restart: unless-stopped
  jackett:
    image: lscr.io/linuxserver/jackett:latest
    container_name: jackett
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    network_mode: "service:gluetun"
    volumes:
      - /config/jackett:/config
      - /data/torrents:/downloads
    restart: unless-stopped
  homarr:
    container_name: homarr
    image: ghcr.io/ajnart/homarr:latest
    restart: unless-stopped
    network_mode: "service:gluetun"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # Optional, only if you want docker integration
      - ./homarr/configs:/app/data/configs
      - ./homarr/icons:/app/public/icons
      - /config/homarr/data:/data
